apiVersion: observability.redhat.com/v1
kind: Observability
metadata:
  name: observability-sample
spec:
  observatorium:
    gateway: "https://observatorium-observatorium.apps-crc.testing"
    token: ""
    tenant: "test"